### PR TITLE
Add API endpoints

### PR DESCRIPTION
**Pull request by alonsofalconi**
### Summary
Added API endpoints with prefix route `/api/` (e.g., localhost:3000/api/users/1/posts/)

#### Details
- Added API endpoint to list all posts.
> Endpoint: [GET] localhost:3000/api/users/1/posts/
image

- Added API endpoint to list comments for a post.
> Endpoint: [GET] localhost:3000/api/users/1/posts/2/
image

- Added API endpoint to create a comment.
> Endpoint: [POST] localhost:3000/api/users/1/posts/2/comments/
> **JSON body must contain "text".**
image

- Added API endpoint to register users.
> Endpoint: [POST] localhost:3000/api/register/
> **JSON body must contain "name", "email", and "password"**
image

- Added API endpoint to authenticate users. The response will be the token authentication (using devise-jwt gem).
> Endpoint: [POST] localhost:3000/api/login/
> **JSON body must contain "email" and "password"**
image

### CODE REVIEW

**Review by Lameck1 — CHANGES_REQUESTED** [review]
Hi @alonsofl & @leonardodiasb, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Every API endpoint works as expected but with one exception, they can all be interacted with without authentication. That means we have missed working on one project requirement, which is quoted below 👇🏼:

* > Add authentication to your API endpoints.

### Hint
Please take a look at this [devise-jwt gem documentation](https://github.com/waiting-for-dev/devise-jwt), it outlines how you can achieve that.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alonsofalconi** [comment]
Thanks for your feedback @Lameck1! The authentication issue has been addressed.
1. When requesting the post list, I get the "Missing token" message.
> [GET] localhost:3000/api/users/1/posts/
image

2. When registering, I get the "User created" message.
> [POST] localhost:3000/api/register
> JSON body: "name": "Demo", "email": "demo@demo.com", "password": "123456"
image

3. When logging in, I get the "auth_token".
> [POST] localhost:3000/api/login
> JSON body: "email": "demo@demo.com", "password": "123456"
image

4. Now, when trying to get the posts with the `auth token` as Bearer I get a confirmation response.
> [GET] localhost:3000/api/users/1/posts/
> JSON body: empty
> Auth - Bearer: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxOSwiZXhwIjoxNjM2ODI0MTE3fQ.lLx1RLrLXg0K73M194_v1NuVNMpfCu1DvEMDkgg6vZA
**The previous auth_token**
image

**Review by Lameck1 — APPROVED** [review]
Hi, @alonsofl & @leonardodiasb,

The tasks for this milestone have been successfully implemented 💯.
All the best with the next milestone.

You are free to merge this branch :shipit:

Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alonsofalconi** [comment]
Thanks, @Lameck1! :muscle:

**Pull request merged**
